# Generated by Django 4.1.1 on 2024-08-30 15:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_remove_car_price_car_name_car_alter_car_date_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('name_car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.car')),
            ],
        ),
    ]
