# Generated by Django 4.1.1 on 2024-08-30 15:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_caroffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('commented_date', models.DateTimeField(default=datetime.datetime.now)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.caroffer')),
            ],
        ),
    ]
